appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HiqVSrKOg1uCqQFlxIcsMGMDAnI/p8pbqrMx7Dq+n3QUsuIKeLn2W+SHI1jqonQlLhjMxjMuiV/2yf1qEV4zKTm/HDpftX4HG83q6LCKTD1LPty8Xo2iEvfoHy5Ck+SkPIAYM+kVx2QwVeJLJaMquZGIKUtkTTECvK7ocSY5+k+gvlzCweTAEfOz9WKnRVZ59SbKOciyzxPBY7O6eGdUa0rU0t43o5I7JKQnkk/mZz8tC0x8b2giVvrGDcgKaQlRKZcRCCg9X27G8SiSVUglcJx5ixzsvuFM6dRSmSgZSJ+TATo+1jooYVeA1UhqFfJNNO0rs5rk60kTujBcdOpgUvqhyv9uM3ut6TVfd4vc3eK+a+iVOTYTcxYGSBIeK53EWhm6njHHFNJg9GuKsErHs1l3nAE3wiyrlOi0C9fADxuLPhiT0SD0Fwk4/MDzrtOO5/4CFV2dbRJRv5PjTs9Gb5I3CY+0tCgYc6X0vRmgcpFuVctCUK4eAcHJ9Y+B1ZqCp8tfAvS0LEqnc9hAY2ybQ8yfuCTwEOZUFDIRP2uhHiDQd3HzG6fqkahGaQvWZNqPg1/tCf7sljb5/mvjmHFAi4tPWS86uJy9e3WFJ4IX3suW5T/njLA5SdIinT1TirJh497ZDMAQUzpYQDhdnldJByjzcYUbjyvi6LqHXkUG4bE=}
provider:
  win: azure
bot:
  automerge: true
